# https://github.com/janosh/awesome-sveltekit/blob/main/site/.eslintrc.yml
env:
  browser: true
  node: true
extends:
  - prettier
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  max-len:
    - error
    - code: 88
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars":
    [error, { argsIgnorePattern: ^_, varsIgnorePattern: ^_ }]
