request: ["get_preferences"]
response:
  message: >
    {
      "animations_on": null,
      "background_animation": null,
      "animation_speed": null,
      "sound_on": false,
      "volume": null
    }
sideEffects:
  disk:
    startStateDirectory: preferences/sound-off-extra-settings
    endStateDirectory: preferences/sound-off-extra-settings
