request: ["get_preferences"]
response:
  message: >
    {
      "sound_on": false
    }
sideEffects:
  disk:
    startStateDirectory: preferences/sound-off-extra-settings
    endStateDirectory: preferences/sound-off-extra-settings
